# MCP Server Configuration
mcp_server:
  url: "http://localhost:8080"
  endpoints:
    tools_list: "/mcp/v1/tools/list"
    tools_call: "/mcp/v1/tools/call"
    sse: "/mcp/v1/sse"
  timeout: 30

# Ollama Configuration
ollama:
  base_url: "http://localhost:11434"
  model: "gpt-oss:20b"
  temperature: 0.7
  num_ctx: 4096
  top_p: 0.9
  timeout: 120

# Chatbot Settings
chatbot:
  name: "MCP Assistant"
  system_prompt: |
    You are a helpful AI assistant with access to SQLite database tools via MCP (Model Context Protocol).
    You can help users create tables, insert records, query data, update records, and delete data.

    When users ask about data operations, use the appropriate tools to help them.
    Always explain what you're doing and show the results clearly.
  max_history: 10
  show_tool_calls: true

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
